services:
  webapp:
    ports:
      - 8000:8000
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    volumes:
      - ./static:/app/staticfiles
