services:
  webapp:
    ports:
      - 8000:8000
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    volumes:
      - ./static:/app/staticfiles

# To start the app run in the terminal:
# docker compose build - to build an image
# docker compose up -d - to start the containers 